services:
  flask-app:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    depends_on:
      - mysql
      - ollama
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - MYSQL_PASSWORD=admin_password
      - OLLAMA_HOST=http://ollama:11434
    volumes:
      - .:/app
    restart: always
    networks:
      - mynetwork

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_db1
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./my_db1_dump.sql:/docker-entrypoint-initdb.d/my_db1_dump.sql  # Auto-import DB
    networks:
      - mynetwork

  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama  # Using a custom Dockerfile for Ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama  # Persistent Ollama model storage
      - ./entrypoint.sh:/entrypoint.sh  # Ensure proper entrypoint script
    tty: true
    restart: always
    entrypoint: ["/bin/bash", "/entrypoint.sh"]
    networks:
      - mynetwork

volumes:
  mysql_data:
  ollama_data:  # Ensure persistent Ollama storage

networks:
  mynetwork:
    driver: bridge
